### PR TITLE
allow printing to specific device

### PR DESCRIPTION
**Pull request by fenollp**

### CODE REVIEW

**Comment by fenollp** [comment]
Not sure how having 2 successive optional arguments works for backward compatibility. Should I move the device inside `opts`?

**Comment by hpopp** [comment]
Instead of changing the arity, why not just make a `:device` option?

Edit: Great minds think alike 😅. That's what I get for not reading everything before commenting.

**Comment by fenollp** [comment]
Ready :)

**Comment by fenollp** [comment]
Should I do any more changes @hpopp @codedge-llc?

**Comment by hpopp** [comment]
Sorry, tied up with a lot of work lately. For legibility's sake, I would assign `results |> format(opts)` to a variable instead of doing the pipe inside `IO.puts`. Looks fine otherwise, I'll cut a new release once you make the change.

**Comment by fenollp** [comment]
Done! Would love a release :) Thanks!

**Comment by hpopp** [comment]
👍

**Pull request merged**
