### PR TITLE
Feature/pseudo graphics

### PR DESCRIPTION
**Pull request by am-kantox**
Adds a pseudographics to draw nifty table without damn spacing between dashes.

### CODE REVIEW

**Comment by hpopp** [comment]
Love it. Can you update the style to match how its shown in the README? Current implementation has lines between every row.

**Comment by am-kantox** [comment]
I am not sure I follow. If you are talking about spaces [here](https://github.com/codedge-llc/scribe/pull/6/files#diff-04c6e90faac2675aa89e2176d2eec7d8R214), it’s github HTML linespacing, in console there are no spaces.

**Comment by hpopp** [comment]
```elixir
describe "pseudo" do
    test "outputs correct format" do
      t = %Scribe.StyleTest{}
      refute t.id
      assert t.value == 1234

      # Whitespace stripping breaks docstrings
      expected =
        "┌────────────────────┬───────┬──────────┐\n" <>
        "│ :__struct__        │ :id   │ :value   │\n" <>
        "├────────────────────┼───────┼──────────┤\n" <>
        "│ Scribe.StyleTest   │ nil   │ 1234     │\n" <>
        "├────────────────────┼───────┼──────────┤\n" <>
        "│ Scribe.StyleTest   │ nil   │ 1234     │\n" <>
        "├────────────────────┼───────┼──────────┤\n" <>
        "│ Scribe.StyleTest   │ nil   │ 1234     │\n" <>
        "└────────────────────┴───────┴──────────┘\n"

      opts = [colorize: false, style: Scribe.Style.Pseudo]
      actual = Scribe.format([t, t, t], opts)
      assert actual == expected
    end
  end
```

Should actually be testing for:

```elixir
describe "pseudo" do
    test "outputs correct format" do
      t = %Scribe.StyleTest{}
      refute t.id
      assert t.value == 1234

      # Whitespace stripping breaks docstrings
      expected =
        "┌────────────────────┬───────┬──────────┐\n" <>
        "│ :__struct__        │ :id   │ :value   │\n" <>
        "├────────────────────┼───────┼──────────┤\n" <>
        "│ Scribe.StyleTest   │ nil   │ 1234     │\n" <>
        "│ Scribe.StyleTest   │ nil   │ 1234     │\n" <>
        "│ Scribe.StyleTest   │ nil   │ 1234     │\n" <>
        "└────────────────────┴───────┴──────────┘\n"

      opts = [colorize: false, style: Scribe.Style.Pseudo]
      actual = Scribe.format([t, t, t], opts)
      assert actual == expected
    end
  end
```

**Comment by am-kantox** [comment]
Ah, indeed :)

Fixed.

**Pull request merged**
